# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pic_Changer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui 
from assets.controller import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 411, 211))
        self.tabWidget.setObjectName("tabWidget")

        # ************************************************************
        # *********************** Re Name Tab ************************
        # ************************************************************
        self.reNameTab = QtWidgets.QWidget()
        self.reNameTab.setObjectName("reNameTab")
        self.reNameLabel = QtWidgets.QLabel(self.reNameTab)
        self.reNameLabel.setGeometry(QtCore.QRect(10, 10, 110, 13))
        self.reNameLabel.setObjectName("reNameLabel")
        self.newNameLabe = QtWidgets.QLabel(self.reNameTab)
        self.newNameLabe.setGeometry(QtCore.QRect(10, 80, 80, 13))
        self.newNameLabe.setObjectName("newNameLabe")
        self.routeInput = QtWidgets.QLineEdit(self.reNameTab)
        self.routeInput.setGeometry(QtCore.QRect(10, 40, 381, 21))
        self.routeInput.setObjectName("routeInput")
        self.nameInput = QtWidgets.QLineEdit(self.reNameTab)
        self.nameInput.setGeometry(QtCore.QRect(10, 110, 381, 20))
        self.nameInput.setObjectName("nameInput")
        self.reNameButton = QtWidgets.QToolButton(self.reNameTab)
        self.reNameButton.setGeometry(QtCore.QRect(160, 150, 81, 21))
        self.reNameButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reNameButton.setObjectName("reNameButton")
        self.reNameButton.clicked.connect(self.changeName)
        self.nameInput.returnPressed.connect(self.reNameButton.click)
        self.tabWidget.addTab(self.reNameTab, "")
        
        # ************************************************************
        # ********************* Delete Name Tab **********************
        # ************************************************************
        self.deleteNameTab = QtWidgets.QWidget()
        self.deleteNameTab.setObjectName("deleteNameTab")
        self.deleteNameLabel = QtWidgets.QLabel(self.deleteNameTab)
        self.deleteNameLabel.setGeometry(QtCore.QRect(10, 10, 110, 13))
        self.deleteNameLabel.setObjectName("deleteNameLabel")
        self.deleteNameInput = QtWidgets.QLineEdit(self.deleteNameTab)
        self.deleteNameInput.setGeometry(QtCore.QRect(10, 40, 381, 21))
        self.deleteNameInput.setObjectName("deleteNameInput")
        self.changeNameLabel = QtWidgets.QLabel(self.deleteNameTab)
        self.changeNameLabel.setGeometry(QtCore.QRect(10, 80, 110, 13))
        self.changeNameLabel.setObjectName("changeNameLabel")
        self.changeNameInput = QtWidgets.QLineEdit(self.deleteNameTab)
        self.changeNameInput.setGeometry(QtCore.QRect(10, 110, 381, 20))
        self.changeNameInput.setObjectName("changeNameInput")
        self.deleteNameButton = QtWidgets.QToolButton(self.deleteNameTab)
        self.deleteNameButton.setGeometry(QtCore.QRect(160, 150, 81, 21))
        self.deleteNameButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteNameButton.setObjectName("deleteNameButton")
        self.changeNameInput.returnPressed.connect(self.deleteNameButton.click)
        self.deleteNameButton.clicked.connect(self.deleteName)
        self.tabWidget.addTab(self.deleteNameTab, "")

        # ************************************************************
        # *********************** Converter **************************
        # ************************************************************
        self.converter = QtWidgets.QWidget()
        self.converter.setObjectName("converter")
        self.converterLabel = QtWidgets.QLabel(self.converter)
        self.converterLabel.setGeometry(QtCore.QRect(10, 10, 110, 13))
        self.converterLabel.setObjectName("converterLabel")
        self.converterInput = QtWidgets.QLineEdit(self.converter)
        self.converterInput.setGeometry(QtCore.QRect(10, 40, 381, 21))
        self.converterInput.setObjectName("converterInput")
        self.fromLabel = QtWidgets.QLabel(self.converter)
        self.fromLabel.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.fromLabel.setObjectName("fromLabel")
        self.toLabel = QtWidgets.QLabel(self.converter)
        self.toLabel.setGeometry(QtCore.QRect(210, 80, 47, 13))
        self.toLabel.setObjectName("toLabel")
        self.fromComboBox = QtWidgets.QComboBox(self.converter)
        self.fromComboBox.setGeometry(QtCore.QRect(90, 80, 69, 22))
        self.fromComboBox.setObjectName("fromComboBox")
        self.fromComboBox.addItem("")
        self.fromComboBox.addItem("")
        self.fromComboBox.addItem("")
        self.fromComboBox.addItem("")
        self.fromComboBox.addItem("")
        self.toComboBox = QtWidgets.QComboBox(self.converter)
        self.toComboBox.setGeometry(QtCore.QRect(320, 80, 69, 22))
        self.toComboBox.setObjectName("toComboBox")
        self.toComboBox.addItem("")
        self.toComboBox.addItem("")
        self.converterButton = QtWidgets.QToolButton(self.converter)
        self.converterButton.setGeometry(QtCore.QRect(160, 150, 81, 21))
        self.converterButton.setObjectName("converterButton")
        self.converterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.converterButton.clicked.connect(self.convertFiles)
        self.tabWidget.addTab(self.converter, "")

        # ************************************************************
        # ************************ Enhance ***************************
        # ************************************************************
        self.enhance = QtWidgets.QWidget()
        self.enhance.setObjectName("enhance")
        self.enhanceLabel = QtWidgets.QLabel(self.enhance)
        self.enhanceLabel.setGeometry(QtCore.QRect(10, 10, 110, 13))
        self.enhanceLabel.setObjectName("enhanceLabel")
        self.enhanceInput = QtWidgets.QLineEdit(self.enhance)
        self.enhanceInput.setGeometry(QtCore.QRect(10, 40, 381, 21))
        self.enhanceInput.setObjectName("enhanceInput")
        self.enhanceButton = QtWidgets.QToolButton(self.enhance)
        self.enhanceButton.setGeometry(QtCore.QRect(160, 150, 81, 21))
        self.enhanceButton.setObjectName("enhanceButton")
        self.enhanceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enhanceInput.returnPressed.connect(self.enhanceButton.click)
        self.enhanceButton.clicked.connect(self.enhanceFiles)
        self.tabWidget.addTab(self.enhance, "")

        # ************************************************************
        # *********************** Menu Bar ***************************
        # ************************************************************
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 407, 21))
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.menuConfig.addAction(self.actionLanguage)

        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pic Management"))
        # *********************** Re Name Tab ************************
        self.reNameLabel.setText(_translate("MainWindow", "Ruta de las imágenes"))
        self.newNameLabe.setText(_translate("MainWindow", "Nuevo nombre"))
        self.reNameButton.setText(_translate("MainWindow", "Ok"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reNameTab), _translate("MainWindow", "Renombrar"))
        # ********************* Delete Name Tab **********************
        self.deleteNameLabel.setText(_translate("MainWindow", "Ruta de las imágenes"))
        self.changeNameLabel.setText(_translate("MainWindow", "Quitar texto"))
        self.deleteNameButton.setText(_translate("MainWindow", "Ok"))
        self    .tabWidget.setTabText(self.tabWidget.indexOf(self.deleteNameTab), _translate("MainWindow", "Eliminar"))
        # *********************** Converter **************************
        self.converterLabel.setText(_translate("MainWindow", "Ruta de las imágenes"))
        self.fromLabel.setText(_translate("MainWindow", "De: "))
        self.toLabel.setText(_translate("MainWindow", "a: "))
        self.converterButton.setText(_translate("MainWindow", "Convertir"))
        self.fromComboBox.setItemText(0, QtCore.QCoreApplication.translate("MainWindow", u"Todo", None))
        self.fromComboBox.setItemText(1, QtCore.QCoreApplication.translate("MainWindow", u"webp", None))
        self.fromComboBox.setItemText(2, QtCore.QCoreApplication.translate("MainWindow", u"jpg", None))
        self.fromComboBox.setItemText(3, QtCore.QCoreApplication.translate("MainWindow", u"jpeg", None))
        self.fromComboBox.setItemText(4, QtCore.QCoreApplication.translate("MainWindow", u"png", None))
        self.toComboBox.setItemText(0, QtCore.QCoreApplication.translate("MainWindow", u"png", None))
        self.toComboBox.setItemText(1, QtCore.QCoreApplication.translate("MainWindow", u"webp", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.converter), _translate("MainWindow", "Convertir"))
        # ************************ Enhance ***************************
        self.enhanceLabel.setText(_translate("MainWindow", "Ruta de las imágenes"))
        self.enhanceButton.setText(_translate("MainWindow", "Mejorar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.enhance), _translate("MainWindow", "Mejorar"))
        # ************************ Menu Bar **************************
        self.menuConfig.setTitle(_translate("MainWindow", "Configuración"))
        self.menuHelp.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionLanguage.setText(QtCore.QCoreApplication.translate("MainWindow", u"Idioma", None))
        self.actionAbout.setText(QtCore.QCoreApplication.translate("MainWindow", u"Acerca de", None))
    
    def changeName(self):
        self.reNameAction = ReName()
        folder = self.routeInput.text()
        name = self.nameInput.text()
        
        try:
            self.reNameAction.New_Name(folder, name)
            message = "Se cambiaron los nombres"
            QtWidgets.QMessageBox.information(self.centralwidget, "Aviso", message)
        except Exception as ex:
            error_message = "Se produjo un error al cambiar el nombre:\n\n{}".format(str(ex))
            QtWidgets.QMessageBox.critical(self.centralwidget, "Error", error_message)
        finally:
            self.routeInput.setText("")
            self.nameInput.setText("")

    def deleteName(self):
        self.reNameAction = ReName()
        folder = self.deleteNameInput.text()
        name = self.changeNameInput.text()
        
        try:
            self.reNameAction.Delete_Name(folder, name)
            message = "Se cambiaron los nombres"
            QtWidgets.QMessageBox.information(self.centralwidget, "Aviso", message)
        except Exception as ex:
            error_message = "Se produjo un error al cambiar el nombre:\n\n{}".format(str(ex))
            QtWidgets.QMessageBox.critical(self.centralwidget, "Error", error_message)
        finally:
            self.deleteNameInput.setText("")
            self.changeNameInput.setText("")

    def convertFiles(self):
        self.convertImg = convert()
        folder = self.converterInput.text()
        currentFile = self.fromComboBox.currentText()
        newFile = self.toComboBox.currentText()
        try:
            self.convertImg.convert(folder, currentFile, newFile)
            message = "Se cambio la extension de los archivos"
            QtWidgets.QMessageBox.information(self.centralwidget, "Aviso", message)
        except Exception as ex:
            error_message = "Se produjo un error al cambiar la extension:\n\n{}".format(str(ex))
            QtWidgets.QMessageBox.critical(self.centralwidget, "Error", error_message)
        finally:
            self.converterInput.setText("")
    def enhanceFiles(self):
        self.enhanceImg = enhance()
        folder = self.enhanceInput.text()
        try:
            self.enhanceImg.enhance(folder)
        except Exception as ex:
            error_message = "Se produjo un error al mejorar la imagen:\n\n{}".format(str(ex))
            QtWidgets.QMessageBox.critical(self.centralwidget, "Error", error_message)









        

